CREATE DATABASE 'mscws';
CREATE USER 'mscws'@'localhost' IDENTIFIED BY 'mscws';
GRANT ALL PRIVILEGES ON mscws. * TO 'mscws'@'localhost';




insert into providertype values (2 ,"Slot Contractor");
insert into providertype values (3,"Group Home");
insert into providertype values (4 ,"Center");
insert into providertype values (5 ,"Non-Relative In-Home");
insert into providertype values (6 ,"Relative In-Home");
insert into providertype values (7 ,"Non-Relative Out-of-Home");
insert into providertype values (8 ,"Relative Out-of-Home");


insert into qualityrating values (0, "Not Rated");
insert into qualityrating values (1, "Low");
insert into qualityrating values (2, "Average");
insert into qualityrating values (3, "Good");
insert into qualityrating values (4, "Very Good");
insert into qualityrating values (5, "Excellent");

insert into county values (1, "ADAMS");
insert into county values (2, "ALCORN");
insert into county values (3 , "AMITE");
insert into county values (4 , "ATTALA");
insert into county values (5 , "BENTON");
insert into county values (6 , "BOLIVAR");
insert into county values (7 , "CALHOUN");
insert into county values (8 , "CARROLL");
insert into county values (9 , "CHICKASAW");
insert into county values (10 , "CHOCTAW");
insert into county values (11 , "CLAIBORNE");
insert into county values (12 , "CLARKE");
insert into county values (13 , "CLAY");
insert into county values (14 , "COAHOMA");
insert into county values (15 , "COPIAH");
insert into county values (16, "COVINGTON");
insert into county values (17 , "DESOTO");
insert into county values (18 , "FORREST");
insert into county values (19 , "FRANKLIN");
insert into county values (20 , "GEORGE");
insert into county values (21 , "GREENE");
insert into county values (22 , "GRENADA");
insert into county values (23 , "HANCOCK");
insert into county values (24 , "HARRISON");
insert into county values (25 , "HINDS");
insert into county values (26 , "HOLMES");
insert into county values (27 , "HUMPHREYS");
insert into county values (28 , "ISSAQUENA");
insert into county values (29 , "ITAWAMBA");
insert into county values (30 , "JACKSON");
insert into county values (31 , "JASPER");
insert into county values (32 , "JEFFERSON");
insert into county values (33 , "JEFFERSON DAVIS");
insert into county values (34 , "JONES");
insert into county values (35 , "KEMPER");
insert into county values (36 , "LAFAYETTE");
insert into county values (37 , "LAMAR");
insert into county values (38 , "LAUDERDALE");
insert into county values (39 , "LAWRENCE");
insert into county values (40 , "LEAKE");
insert into county values (41 , "LEE");
insert into county values (42 , "LEFLORE");
insert into county values (43 , "LINCOLN");
insert into county values (44 , "LOWNDES");
insert into county values (45 , "MADISON");
insert into county values (46 , "MARION");
insert into county values (47 , "MARSHALL");
insert into county values (48 , "MONROE");
insert into county values (49 , "MONTGOMERY");
insert into county values (50 , "NESHOBA");
insert into county values (51 , "NEWTON");
insert into county values (52 , "NOXUBEE");
insert into county values (53 , "OKTIBBEHA");
insert into county values (54 , "PANOLA");
insert into county values (55 , "PEARL RIVER");
insert into county values (56 , "PERRY");
insert into county values (57 , "PIKE");
insert into county values (58 , "PONTOTOC");
insert into county values (59 , "PRENTISS");
insert into county values (60 , "QUITMAN");
insert into county values (61 , "RANKIN");
insert into county values (62 , "SCOTT");
insert into county values (63 , "SHARKEY");
insert into county values (64 , "SIMPSON");
insert into county values (65 , "SMITH");
insert into county values (66 , "STONE");
insert into county values (67 , "SUNFLOWER");
insert into county values (68 , "TALLAHATCHIE");
insert into county values (69 , "TATE");
insert into county values (70 , "TIPPAH");
insert into county values (71 , "TISHOMINGO");
insert into county values (72 , "TUNICA");
insert into county values (73 , "UNION");
insert into county values (74 , "WALTHALL");
insert into county values (75 , "WARREN");
insert into county values (76 , "WASHINGTON");
insert into county values (77 , "WAYNE");
insert into county values (78 , "WEBSTER");
insert into county values (79 , "WILKINSON");
insert into county values (80 , "WINSTON");
insert into county values (81 , "YALOBUSHA");
insert into county values (82 , "YAZOO");
